import { LogoMeta, Direction, HighlightRange } from "./types/shared";
import { Font } from "opentype.js";
export declare class LogoGenerator {
    readonly origWidth = 1280;
    readonly origHeight = 720;
    readonly largeCellSize = 132;
    readonly smallCellSize: number;
    readonly backgroundBoxRadius = 8;
    readonly backgroundStrokeWidth = 6;
    readonly spacing = 12;
    readonly lineSpacing = 4;
    readonly lineMaxLength: number[];
    document: Document;
    width: number;
    height: number;
    meta: LogoMeta;
    direction: Direction;
    fonts: Map<string, Font>;
    constructor(meta?: LogoMeta, direction?: Direction);
    setMeta(meta: LogoMeta): void;
    private getCellSize;
    private calcLineWidth;
    private calcLineHeight;
    private calcLinesHeight;
    private loadFont;
    private drawBackground;
    private drawChar;
    private drawLine;
    generate(firstLine: string, secondLine: string, highlights?: HighlightRange[], center?: boolean): Promise<SVGSVGElement>;
}
